import Head from "next/head";

export async function getStaticProps() {
	const data = await fetch("https://jsonplaceholder.typicode.com/posts");
	const posts = await data.json();
	return {
		props: { posts },
	};
}

const Projects = ({ posts }) => {
	return (
		<>
			<Head>
				<title>NextJS | Projects</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				You can see my projects here <br />
				For testing i'm displaying fake posts data for now...
			</div>
			{posts.slice(0, 9).map((post) => (
				<div>
					<h3>userId: {post.userId}</h3> <br />
					postId: {post.id} <br />
					title: {post.title}
				</div>
			))}
		</>
	);
};

export default Projects;
