import Head from "next/head";

const About = () => {
	return (
		<>
			<Head>
				<title>NextJS | About</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>You can find more about me here....</div>
		</>
	);
};

export default About;
