import Head from "next/head";
// import Image from 'next/image'
// import { Inter } from '@next/font/google'

export default function Home() {
	return (
		<>
			<Head>
				<title>NextJS | Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div>
					My name is Muhammad Salman. I'm 20 years old Software Engineer at Metadots. I'm doing my bachelor's from PUCIT
					New Campus, Lahore.
				</div>
			</main>
		</>
	);
}
